### ISSUE TITLE
AI based auto-generate code required

### ISSUE THREAD

**Issue by IntuzMayankP** [doralteres/express-sequelize-autocrud#80]
@doralteres 

**We need below requirement** 

- We need an AI tool to auto-generate the source code
- Developers can generate basic CRUD-based source code (routing, controller, model) with database-supported files (like migration, schema, and seeder).
- It should be compatible with the current source code architecture
- MySQL Database using Sequelize ORM

Is your platform will fulfill my requirement?

**Comment by doralteres** [comment]
Hello there is no AI involved in that module. you can use some ai generation out of the module scope and feed the autocrud with AI-generated based config
